name: Publish package to npm and pypi

on:
  push:
    branches: ["with-generated-files"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@14265627712d996af2c85773c9eab5bfecd3660f
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    with:
      node-version: '20.12.1'
